/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppProntuariosRouteImport } from './routes/_authenticated/app.prontuarios'
import { Route as AuthenticatedAppPacientesRouteImport } from './routes/_authenticated/app.pacientes'
import { Route as AuthenticatedAppFinanceiroRouteImport } from './routes/_authenticated/app.financeiro'
import { Route as AuthenticatedAppConfiguracoesRouteImport } from './routes/_authenticated/app.configuracoes'
import { Route as AuthenticatedAppAgendaRouteImport } from './routes/_authenticated/app.agenda'
import { Route as AuthenticatedAppProntuariosIndexRouteImport } from './routes/_authenticated/app.prontuarios.index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProntuariosRoute =
  AuthenticatedAppProntuariosRouteImport.update({
    id: '/prontuarios',
    path: '/prontuarios',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPacientesRoute =
  AuthenticatedAppPacientesRouteImport.update({
    id: '/pacientes',
    path: '/pacientes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFinanceiroRoute =
  AuthenticatedAppFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppConfiguracoesRoute =
  AuthenticatedAppConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAgendaRoute = AuthenticatedAppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProntuariosIndexRoute =
  AuthenticatedAppProntuariosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppProntuariosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/app/pacientes': typeof AuthenticatedAppPacientesRoute
  '/app/prontuarios': typeof AuthenticatedAppProntuariosRouteWithChildren
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/prontuarios/': typeof AuthenticatedAppProntuariosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/app/pacientes': typeof AuthenticatedAppPacientesRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/prontuarios': typeof AuthenticatedAppProntuariosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/_authenticated/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/_authenticated/app/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/_authenticated/app/pacientes': typeof AuthenticatedAppPacientesRoute
  '/_authenticated/app/prontuarios': typeof AuthenticatedAppProntuariosRouteWithChildren
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/prontuarios/': typeof AuthenticatedAppProntuariosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/app'
    | '/app/agenda'
    | '/app/configuracoes'
    | '/app/financeiro'
    | '/app/pacientes'
    | '/app/prontuarios'
    | '/app/'
    | '/app/prontuarios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/app/agenda'
    | '/app/configuracoes'
    | '/app/financeiro'
    | '/app/pacientes'
    | '/app'
    | '/app/prontuarios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/app'
    | '/_authenticated/app/agenda'
    | '/_authenticated/app/configuracoes'
    | '/_authenticated/app/financeiro'
    | '/_authenticated/app/pacientes'
    | '/_authenticated/app/prontuarios'
    | '/_authenticated/app/'
    | '/_authenticated/app/prontuarios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/prontuarios': {
      id: '/_authenticated/app/prontuarios'
      path: '/prontuarios'
      fullPath: '/app/prontuarios'
      preLoaderRoute: typeof AuthenticatedAppProntuariosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/pacientes': {
      id: '/_authenticated/app/pacientes'
      path: '/pacientes'
      fullPath: '/app/pacientes'
      preLoaderRoute: typeof AuthenticatedAppPacientesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/financeiro': {
      id: '/_authenticated/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/configuracoes': {
      id: '/_authenticated/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AuthenticatedAppConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/agenda': {
      id: '/_authenticated/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AuthenticatedAppAgendaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/prontuarios/': {
      id: '/_authenticated/app/prontuarios/'
      path: '/'
      fullPath: '/app/prontuarios/'
      preLoaderRoute: typeof AuthenticatedAppProntuariosIndexRouteImport
      parentRoute: typeof AuthenticatedAppProntuariosRoute
    }
  }
}

interface AuthenticatedAppProntuariosRouteChildren {
  AuthenticatedAppProntuariosIndexRoute: typeof AuthenticatedAppProntuariosIndexRoute
}

const AuthenticatedAppProntuariosRouteChildren: AuthenticatedAppProntuariosRouteChildren =
  {
    AuthenticatedAppProntuariosIndexRoute:
      AuthenticatedAppProntuariosIndexRoute,
  }

const AuthenticatedAppProntuariosRouteWithChildren =
  AuthenticatedAppProntuariosRoute._addFileChildren(
    AuthenticatedAppProntuariosRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAgendaRoute: typeof AuthenticatedAppAgendaRoute
  AuthenticatedAppConfiguracoesRoute: typeof AuthenticatedAppConfiguracoesRoute
  AuthenticatedAppFinanceiroRoute: typeof AuthenticatedAppFinanceiroRoute
  AuthenticatedAppPacientesRoute: typeof AuthenticatedAppPacientesRoute
  AuthenticatedAppProntuariosRoute: typeof AuthenticatedAppProntuariosRouteWithChildren
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAgendaRoute: AuthenticatedAppAgendaRoute,
  AuthenticatedAppConfiguracoesRoute: AuthenticatedAppConfiguracoesRoute,
  AuthenticatedAppFinanceiroRoute: AuthenticatedAppFinanceiroRoute,
  AuthenticatedAppPacientesRoute: AuthenticatedAppPacientesRoute,
  AuthenticatedAppProntuariosRoute:
    AuthenticatedAppProntuariosRouteWithChildren,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
